name: pip_services3_mqtt
version: 1.1.1
description: This framework is part of the [Pip.Services](https://github.com/pip-services/pip-services) project. It contains MQTT messaging components.
homepage: https://github.com/pip-services3-dart/pip-services3-mqtt-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  pip_services3_commons: ^1.1.3
  pip_services3_components: ^1.1.2
  pip_services3_messaging: ^1.1.0
  mqtt_client: ^9.6.1
 
dev_dependencies:
  test: ^1.17.12